@baseUrl = http://localhost:3000

POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Example",
  "email": "example@example.com",
  "password": "password123",
  "passwordConfirm": "password123"
}


###
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password123"
}


###
GET {{baseUrl}}/api/users/me


###
POST {{baseUrl}}/api/auth/logout

###
POST http://localhost:3000/api/pix

// ==================== CAMPAIGN ====================
###
GET {{baseUrl}}/api/campaign

###
POST {{baseUrl}}/api/campaign
Content-Type: application/json

{
  "title": "Test campaign sala",
  "description": "Something nice",
  "pixKey": "asssdsdsdsd"
}

###
DELETE {{baseUrl}}/api/campaign/cb460a08-5f2f-46ac-b73d-21d8769ad9c1
