@baseUrl = http://localhost:3000

### Register User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Example",
  "email": "example@example.com",
  "password": "password123"
}


### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password123"
}


### Current User
GET {{baseUrl}}/api/users/me


### Logout
POST {{baseUrl}}/api/auth/logout

### PIX
POST http://localhost:3000/api/pix
Content-Type: application/json

{
  "campaignId": "17e8f7f1-3d0d-4218-a5bd-6b26e8043524",
  "amount": 0.03
}

### Process Transaction
POST http://localhost:3000/api/pix/process-transaction/0013

### Fetch Campaigns
GET {{baseUrl}}/api/campaign

### Register Campaign
POST {{baseUrl}}/api/campaign
Content-Type: application/json

{
  "title": "Test campaisgn sala",
  "description": "Sometshing nice",
  "pixKey": "asssdsdssdsd",
  "imageUrl": "sswwsew",
  "goal": 232.44
}

### Delete Campaign
DELETE {{baseUrl}}/api/campaign/dfe9f852-f381-4344-bf1d-bf588f9dec40

### Update Campaign
PUT  {{baseUrl}}/api/campaign/cde80006-9104-4f7a-a82f-46b6010341d6
Content-Type: application/json

{
  "title": "Test campaign sala",
  "description": "Something nice",
  "imageUrl": null,
  "goal": 55.34,
  "totalRaised": 25.40,
  "pixKey": "asssdsdsdsd"
}

###
POST http://localhost:3000/api/upload
